### ISSUE TITLE
关于文件系统存储

### ISSUE THREAD

**Issue by madcloudsong** [walkor/workerman-statistics#1]
我对这个很统计上报很感兴趣，我看是文件系统存储的，有性能测试么，是否考虑用mysql或者什么替换掉存储部分？

**Comment by walkor** [comment]
这里的文件存储不会有性能问题，因为是定时每分钟写磁盘，每次写入的数据是经过加工计算的统计数据，体积很小，1k左右。

这个统计系统是udp的，吞吐量很强，可以达到数十万每秒的吞吐量。并且这个系统是支持分布式的，可以多机部署，统计结果会自动汇总，使用上就像部署了一台一样。

也没必要存储到mysql或者其它去存储统计数据。

**Comment by madcloudsong** [comment]
谢谢回复～不知道是否还会继续维护完善，比如告警功能或者客户端分视图展现（每一个上报端的数据单独展现，这种需求应该比较常见）

**Comment by walkor** [comment]
告警及其它功能有兴趣可以自行开发，可以的话可以发pr
谢谢 ： ）
